version: '2'

services:
    redis:
        image: redis:latest
        volumes:
        - redis_data:/data
        command: "redis-server --appendonly yes"

    mongo:
        image: mongo:latest
        volumes:
        - mongo_data:/data/db
        command: "--smallfiles"

    web:
        image: thumbsniper/web:latest
        volumes:
        - web_thumbnails:/opt/thumbsniper/web_images/thumbnails
        links:
        - mongo
        - redis
        ports:
        - "80:80"
        networks:
            default:
                aliases:
                    - api.example.com
                    - img.example.com

    agent-normal:
        image: thumbsniper/agent:latest
        links:
        - web
        environment:
        - TAGENT_QUEUE=normal

    agent-longrun:
        image: thumbsniper/agent:latest
        links:
        - web
        environment:
        - TAGENT_QUEUE=longrun

    agent-image:
        image: thumbsniper/agent:latest
        links:
        - web
        environment:
        - TAGENT_QUEUE=image

volumes:
    redis_data:
    mongo_data:
    web_thumbnails:
